### ISSUE TITLE
Create a UI to take multiple pictures

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish-client-capacitor#2]
### Reason

Receipts can be longer than just one picture

### Description

Create a UI where the user can take one or more pictures. The UI should be composed by:
- the camera view (or a "take picture" button)
- a cancel button
- a done button
- a small gridview with the taken pictures preview

### Success Criteria

- [  ] static design of the UI is done and approved

**Comment by mike-audi** [comment]
will not be implemented.
