### ISSUE TITLE
Implement the UI for multiple pictures

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish-client-capacitor#3]
### Reason

The static UI must be usable

### Description

Implement the static UI as a full screen component that is displayed when the function is called. 

The UI should have the following functionality:
1 - take a picture and save it in the list that is stored in-memory
2 - Return an empty list if user cancel the capture
3 - Return a list with the images if the user submit the capture
4 - show the list in the UI's small grid 

### Success Criteria

- [ ] all functionalities pass manual tests
- [ ] integration tests

**Comment by mike-audi** [comment]
will not be implemented
