### ISSUE TITLE
Create Handle Refresh Token

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/publish-client-capacitor#90]
### Reason

Improve business logic and authetication flow

### Description

We should create a method to handle the requests authentication

it should check if the token exists and create a new one if its not

also, if the request returns a code 401, it should call the refresh method to exchange the expired token for a new one and try again (max of 3 attempts)

### Success Criteria

- [ ] a improved handleRequest method

**Comment by ricardobrg** [comment]
@MiroBenicio add the option to determine the max attempts. Default to 3 but if the user wants it can be more
